export const dogBreeds = {
  "Chihuahua": "Chihuahua",
  "Japanese_Spaniel": "Japanischer Spaniel",
  "Maltese": "Malteser",
  "Pekingese": "Pekingese",
  "Shih_Tzu": "Shih Tzu",
  "Blenheim_Spaniel": "Blenheim Spaniel",
  "Papillon": "Papillon",
  "Toy_Terrier": "Toy Terrier",
  "Rhodesian_Ridgeback": "Rhodesian Ridgeback",
  "Afghan_Hound": "Afghanischer Windhund",
  "Basset": "Basset",
  "Beagle": "Beagle",
  "Bloodhound": "Bloodhound",
  "Bluetick": "Bluetick Coonhound",
  "Black_And_Tan_Coonhound": "Black and Tan Coonhound",
  "Walker_Hound": "Walker Hound",
  "English_Foxhound": "English Foxhound",
  "Redbone": "Redbone",
  "Borzoi": "Borzoi",
  "Irish_Wolfhound": "Irish Wolfhound",
  "Italian_Greyhound": "Italian Greyhound",
  "Whippet": "Whippet",
  "Ibizan_Hound": "Ibizan Hound",
  "Norwegian_Elkhound": "Norwegian Elkhound",
  "Otterhound": "Otterhound",
  "Saluki": "Saluki",
  "Scottish_Deerhound": "Scottish Deerhound",
  "Weimaraner": "Weimaraner",
  "Staffordshire_Bullterrier": "Staffordshire Bull Terrier",
  "American_Staffordshire_Terrier": "American Staffordshire Terrier",
  "Bedlington_Terrier": "Bedlington Terrier",
  "Border_Terrier": "Border Terrier",
  "Kerry_Blue_Terrier": "Kerry Blue Terrier",
  "Irish_Terrier": "Irish Terrier",
  "Norfolk_Terrier": "Norfolk Terrier",
  "Norwich_Terrier": "Norwich Terrier",
  "Yorkshire_Terrier": "Yorkshire Terrier",
  "Wire_Haired_Fox_Terrier": "Wire Haired Fox Terrier",
  "Lakeland_Terrier": "Lakeland Terrier",
  "Sealyham_Terrier": "Sealyham Terrier",
  "Airedale": "Airedale Terrier",
  "Cairn": "Cairn Terrier",
  "Australian_Terrier": "Australian Terrier",
  "Dandie_Dinmont": "Dandie Dinmont Terrier",
  "Boston_Bull": "Boston Bull",
  "Miniature_Schnauzer": "Zwergschnauzer",
  "Giant_Schnauzer": "Riesenschnauzer",
  "Standard_Schnauzer": "Schnauzer",
  "Scotch_Terrier": "Scotch Terrier",
  "Tibetan_Terrier": "Tibetan Terrier",
  "Silky_Terrier": "Silky Terrier",
  "Soft_Coated_Wheaten_Terrier": "Soft Coated Wheaten Terrier",
  "West_Highland_White_Terrier": "West Highland White Terrier",
  "Lhasa": "Lhasa Apso",
  "Flat_Coated_Retriever": "Flat Coated Retriever",
  "Curly_Coated_Retriever": "Curly Coated Retriever",
  "Golden_Retriever": "Golden Retriever",
  "Labrador_Retriever": "Labrador Retriever",
  "Chesapeake_Bay_Retriever": "Chesapeake Bay Retriever",
  "German_Short_Haired_Pointer": "German Shorthaired Pointer",
  "Vizsla": "Vizsla",
  "English_Setter": "English Setter",
  "Irish_Setter": "Irish Setter",
  "Gordon_Setter": "Gordon Setter",
  "Brittany_Spaniel": "Brittany Spaniel",
  "Clumber": "Clumber Spaniel",
  "English_Springer": "English Springer Spaniel",
  "Welsh_Springer_Spaniel": "Welsh Springer Spaniel",
  "Cocker_Spaniel": "Cocker Spaniel",
  "Sussex_Spaniel": "Sussex Spaniel",
  "Irish_Water_Spaniel": "Irish Water Spaniel",
  "Kuvasz": "Kuvasz",
  "Schipperke": "Schipperke",
  "Groenendael": "Groenendael",
  "Malinois": "Malinois",
  "Briard": "Briard",
  "Australian_Kelpie": "Australian Kelpie",
  "Komondor": "Komondor",
  "Old_English_Sheepdog": "Old English Sheepdog",
  "Shetland_Sheepdog": "Shetland Sheepdog",
  "Collie": "Collie",
  "Border_Collie": "Border Collie",
  "Bouvier_Des_Flandres": "Bouvier des Flandres",
  "Rottweiler": "Rottweiler",
  "German_Shepherd": "German Shepherd",
  "Doberman": "Doberman Pinscher",
  "Miniature_Pinscher": "Miniature Pinscher",
  "Greater_Swiss_Mountain_Dog": "Greater Swiss Mountain Dog",
  "Bernese_Mountain_Dog": "Bernese Mountain Dog",
  "Appenzeller": "Appenzeller",
  "Entlebucher": "Entlebucher",
  "Boxer": "Boxer",
  "Bull_Mastiff": "Bullmastiff",
  "Tibetan_Mastiff": "Tibetan Mastiff",
  "French_Bulldog": "French Bulldog",
  "Great_Dane": "Great Dane",
  "Saint_Bernard": "Saint Bernard",
  "Eskimo_Dog": "Eskimo Dog",
  "Alaskan_Malamute": "Alaskan Malamute",
  "Siberian_Husky": "Siberian Husky",
  "Affenpinscher": "Affenpinscher",
  "Basenji": "Basenji",
  "Pug": "Pug",
  "Leonberger": "Leonberger",
  "Newfoundland": "Newfoundland",
  "Great_Pyrenees": "Great Pyrenees",
  "Samoyed": "Samoyed",
  "Pomeranian": "Pomeranian",
  "Chow": "Chow Chow",
  "Keeshond": "Keeshond",
  "Brabancon_Griffon": "Griffon Bruxellois",
  "Pembroke_Welsh_Corgi": "Pembroke Welsh Corgi",
  "Cardigan_Welsh_Corgi": "Cardigan Welsh Corgi",
  "Toy_Poodle": "Toy Poodle",
  "Miniature_Poodle": "Miniature Poodle",
  "Standard_Poodle": "Standard Poodle",
  "Mexican_Hairless": "Mexican Hairless",
  "Dingo": "Dingo",
  "Dhole": "Dhole",
  "African_Hunting_Dog": "African Hunting Dog"
};

export const dogBreedLang = {
  en: {
    title: "Dog Breed Classifier",
    description: "Upload a dog photo and AI will identify its breed",
    dragDropText: "Drag and drop a dog image here, or click to select",
    selectButton: "Select Image",
    predictButton: "Identify Breed",
    predicting: "Identifying...",
    clearButton: "Clear",
    resultTitle: "Classification Result",
    breed: "Breed",
    confidence: "Confidence",
    top5Title: "Top 5 Predictions",
    selectImageError: "Please select an image first",
    imageSizeError: "Image size cannot exceed 10MB",
    imageTypeError: "Please select an image file",
    predictError: "Prediction failed, please try again",
    urlHint: "Use direct image links (e.g., from upload.wikimedia.org)"
  },
  de: {
    title: "Hunderassen-Klassifizierung",
    description: "Laden Sie ein Hunderfoto hoch und die KI identifiziert die Rasse",
    dragDropText: "Ziehen Sie ein Hundefoto hierher, oder klicken Sie zum Auswählen",
    selectButton: "Bild auswählen",
    predictButton: "Rasse identifizieren",
    predicting: "Wird identifiziert...",
    clearButton: "Löschen",
    resultTitle: "Klassifizierungsergebnis",
    breed: "Rasse",
    confidence: "Konfidenz",
    top5Title: "Top 5 Vorhersagen",
    selectImageError: "Bitte wählen Sie zuerst ein Bild",
    imageSizeError: "Bildgröße darf 10MB nicht überschreiten",
    imageTypeError: "Bitte wählen Sie eine Bilddatei",
    predictError: "Vorhersage fehlgeschlagen, versuchen Sie es später erneut",
    urlHint: "Verwenden Sie direkte Bild-Links (z.B. von upload.wikimedia.org)"
  }
};

export const getBreedName = (breedEn, language = "en") => {
  if (language === "de") {
    return dogBreeds[breedEn] || breedEn;
  }
  return breedEn;
};