// 120 种犬种的英文和德文名称
export const dogBreeds = {
  "Chihuahua": "Chihuahua",
  "Japanese Chin": "Japanischer Chin",
  "Maltese": "Malteser",
  "Pekinese": "Pekingese",
  "Shih Tzu": "Shih Tzu",
  "Blenheim spaniel": "Blenheim Spaniel",
  "Papillon": "Papillon",
  "Toy Terrier": "Toy Terrier",
  "Rhodesian Ridgeback": "Rhodesian Ridgeback",
  "Afgahn Hound": "Afghanen-Windhund",
  "Basset Hound": "Basset Hound",
  "Beagle": "Beagle",
  "Bloodhound": "Bloodhound",
  "Briard": "Briard",
  "Cocker Spaniel": "Cocker Spaniel",
  "English Setter": "English Setter",
  "Gordon Setter": "Gordon Setter",
  "Great Dane": "Deutsche Dogge",
  "German Shorthaired Pointer": "Deutsch Kurzhaar",
  "Irish Setter": "Irish Setter",
  "Irish Water Spaniel": "Irish Water Spaniel",
  "Keeshond": "Keeshond",
  "Kuvasz": "Kuvasz",
  "Leonberger": "Leonberger",
  "Newfoundland": "Neufundländer",
  "Otter Hound": "Otter Hound",
  "Pointer": "Pointer",
  "Poodle": "Pudel",
  "Saint Bernard": "Bernhardin",
  "Saluki": "Saluki",
  "Samoyed": "Samojede",
  "Scottish Deerhound": "Scottish Deerhound",
  "Weimaraner": "Weimaraner",
  "Welsh Springer Spaniel": "Welsh Springer Spaniel",
  "West Highland White Terrier": "West Highland White Terrier",
  "Wheaten Terrier": "Wheaten Terrier",
  "Wirehaired Pointing Griffon": "Drahthaariger Vorstehhund",
  "Yorkshire Terrier": "Yorkshire Terrier",
  "Airedale": "Airedale Terrier",
  "Bedlington Terrier": "Bedlington Terrier",
  "Border Terrier": "Border Terrier",
  "Boston Bull": "Boston Bull Terrier",
  "Bull Terrier": "Bull Terrier",
  "Cairn": "Cairn Terrier",
  "Dandie Dinmont": "Dandie Dinmont Terrier",
  "Fox Terrier": "Fox Terrier",
  "Irish Terrier": "Irish Terrier",
  "Kerry Blue Terrier": "Kerry Blue Terrier",
  "Lakeland Terrier": "Lakeland Terrier",
  "Manchester Terrier": "Manchester Terrier",
  "Miniature Pinscher": "Zwergpinscher",
  "Miniature Schnauzer": "Zwergschnauzer",
  "Norfolk Terrier": "Norfolk Terrier",
  "Norwich Terrier": "Norwich Terrier",
  "Schnauzer": "Schnauzer",
  "Soft-coated Wheaten Terrier": "Soft-coated Wheaten Terrier",
  "Staffordshire Bull Terrier": "Staffordshire Bull Terrier",
  "American Staffordshire Terrier": "American Staffordshire Terrier",
  "Tibetan Terrier": "Tibetanischer Terrier",
  "Toy Poodle": "Toy Pudel",
  "Welsh Terrier": "Welsh Terrier",
  "Affenpinscher": "Affenpinscher",
  "Basenji": "Basenji",
  "Bernese Mountain Dog": "Berner Sennenhund",
  "Bobtail": "Old English Sheepdog",
  "Borzoi": "Borsoi",
  "Bouvier des Flandres": "Bouvier des Flandres",
  "Boxer": "Boxer",
  "Brabancon": "Brabançon",
  "Brittany Spaniel": "Brittany Spaniel",
  "Bull Mastiff": "Bullmastiff",
  "Canaan Dog": "Canaan Dog",
  "Chesapeake Bay Retriever": "Chesapeake Bay Retriever",
  "Chow": "Chow Chow",
  "Chow Chow": "Chow Chow",
  "Clumber": "Clumber Spaniel",
  "Curly-coated Retriever": "Curly-Coated Retriever",
  "Dachshund": "Dackel",
  "Dalmatian": "Dalmatiner",
  "Dandie Dinmont Terrier": "Dandie Dinmont Terrier",
  "Deerhound": "Scottish Deerhound",
  "Dhole": "Dhole",
  "Dingo": "Dingo",
  "Doberman": "Dobermann",
  "English Foxhound": "English Foxhound",
  "English Springer Spaniel": "English Springer Spaniel",
  "Entlebucher": "Entlebucher Sennenhund",
  "Eskimo Dog": "Eskimo Dog",
  "Flat-Coated Retriever": "Flat-Coated Retriever",
  "French Bulldog": "Französische Bulldogge",
  "German Pinscher": "Deutscher Pinscher",
  "German Shepherd": "Deutscher Schäferhund",
  "German Shepherd Dog": "Deutscher Schäferhund",
  "Giant Schnauzer": "Riesenschnauzer",
  "Golden Retriever": "Golden Retriever",
  "Gordon Setter": "Gordon Setter",
  "Groenendael": "Groenendael",
  "Great Pyrenees": "Großer Schweizer Sennenhund",
  "Greater Swiss Mountain Dog": "Großer Schweizer Sennenhund",
  "Greyhound": "Greyhound",
  "Griffon Bruxellois": "Griffon Bruxellois",
  "Groenendael": "Groenendael",
  "Hound": "Jagdhund",
  "Husky": "Husky",
  "Ibizan Hound": "Ibizan Hound",
  "Irish Red and White Setter": "Irish Red and White Setter",
  "Irish Setter": "Irish Setter",
  "Irish Terrier": "Irish Terrier",
  "Irish Water Spaniel": "Irish Water Spaniel",
  "Irish Wolfhound": "Irish Wolfhound",
  "Italian Greyhound": "Italienischer Windhund",
  "Jack Russell Terrier": "Jack Russell Terrier",
  "Japanese Chin": "Japanischer Chin",
  "Keeshond": "Keeshond",
  "Kelpie": "Kelpie",
  "Kerry Blue Terrier": "Kerry Blue Terrier",
  "Komondor": "Komondor",
  "Kooikerhondje": "Kooikerhondje",
  "Kuvasz": "Kuvasz",
  "Labrador Retriever": "Labrador Retriever",
  "Lakeland Terrier": "Lakeland Terrier",
  "Lakeland": "Lakeland Terrier"
};

// 英文语言配置
export const dogBreedLang = {
  en: {
    title: "🐕 Dog Breed Classifier",
    description: "Upload a dog photo and AI will identify the breed",
    selectImage: "Choose image or drag file",
    predict: "Identify",
    identifying: "Identifying...",
    clear: "Clear",
    result: "Classification Result",
    confidence: "Confidence",
    topResults: "Top 5 Results",
    error: "Error",
    selectImageError: "Please select an image first",
    imageSizeError: "Image size cannot exceed 10MB",
    imageTypeError: "Please select an image file",
    predictError: "Prediction failed, please try again",
    powered: "Powered by Vision Transformer (HF Spaces)"
  },
  de: {
    title: "🐕 Hunderassen-Klassifizierung",
    description: "Laden Sie ein Hunderfoto hoch und die KI identifiziert die Rasse",
    selectImage: "Bild wählen oder Datei ziehen",
    predict: "Identifizieren",
    identifying: "Identifizierung läuft...",
    clear: "Löschen",
    result: "Klassifizierungsergebnis",
    confidence: "Konfidenz",
    topResults: "Top 5 Ergebnisse",
    error: "Fehler",
    selectImageError: "Bitte wählen Sie zuerst ein Bild",
    imageSizeError: "Bildgröße darf 10MB nicht überschreiten",
    imageTypeError: "Bitte wählen Sie eine Bilddatei",
    predictError: "Vorhersage fehlgeschlagen, versuchen Sie es später erneut",
    powered: "Unterstützt von Vision Transformer (HF Spaces)"
  }
};

// 获取本地化的狗种名称
export const getBreedName = (breedEn, language = 'en') => {
  if (language === 'de') {
    return dogBreeds[breedEn] || breedEn;
  }
  return breedEn;
};
